background_images:
  - https://secure.meetupstatic.com/photos/event/6/7/8/f/highres_525326511.webp
  - https://secure.meetupstatic.com/photos/event/6/7/9/0/highres_525326512.webp
  - https://secure.meetupstatic.com/photos/event/6/7/9/7/highres_525326519.webp
  - https://secure.meetupstatic.com/photos/event/6/7/9/b/highres_525326523.webp
  - https://secure.meetupstatic.com/photos/event/2/8/2/9/highres_525850281.webp
  - https://secure.meetupstatic.com/photos/event/2/8/2/a/highres_525850282.webp
  - https://secure.meetupstatic.com/photos/event/2/8/2/c/highres_525850284.webp
  - https://secure.meetupstatic.com/photos/event/2/8/3/0/highres_525850288.webp
  - https://secure.meetupstatic.com/photos/event/2/a/6/a/highres_525850858.webp
  - https://secure.meetupstatic.com/photos/event/2/a/6/e/highres_525850862.webp
  - https://secure.meetupstatic.com/photos/event/2/a/7/0/highres_525850864.webp
  - https://secure.meetupstatic.com/photos/event/2/a/7/1/highres_525850865.webp
  - https://secure.meetupstatic.com/photos/event/2/a/7/7/highres_525850871.webp
  - https://secure.meetupstatic.com/photos/event/3/d/1/0/highres_525195632.webp
  - https://secure.meetupstatic.com/photos/event/3/c/f/e/highres_525195614.webp

gittogethers:
  description: "Registrations close 2 days before the event."
  no_events_message: "No GitTogethers are scheduled at the moment. Please check <a href='https://gh.io/meetups'>gh.io/meetups</a> for more information."
  upcoming:
    - name: "Bengaluru (8th March 2025)"
      end_time: "2025-03-08T17:00:00+05:30"
      confirmation_date: "2025-03-06T23:59:00+05:30"
    - name: "Hyderabad (8th March 2025)"
      end_time: "2025-03-08T17:00:00+05:30"
      confirmation_date: "2025-03-06T23:59:00+05:30"
    - name: "Mumbai (8th March 2025)"
      end_time: "2025-03-08T17:00:00+05:30"
      confirmation_date: "2025-03-06T23:59:00+05:30"

thank_you_message: |
  For queries related to GitTogethers, you can reach out to the community leader in your city. For all other queries, you can reach out to <a href="mailto:meetups@github.com">meetups@github.com</a>

thank_you_buttons:
  - text: "Join WhatsApp Channel for Updates üì¢"
    url: "https://gh.io/meetups/wa"
  - text: "Apply to be a Speaker ‚≠êÔ∏è"
    url: "https://gh.io/cfs"
  - text: "Apply for Community Spotlight üí°"
    url: "https://gh.io/spotlight" 
